{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.fastgit.org/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".local/bin/z.lua"]
    type = "file"
    url = "https://raw.fastgit.org/skywind3000/z.lua/master/z.lua"
    executable = true

{{- if eq .chezmoi.os "linux" }}
{{- $bwcliVersion :="2022.9.0"}}
[".local/bin/bw"]
    type = "file"
    url = "https://download.fastgit.org/bitwarden/clients/releases/download/cli-v{{$bwcliVersion}}/bw-{{ .chezmoi.os }}-{{ $bwcliVersion }}.zip"
    executable = true
    [".local/bin/bw".filter]
        command = "zcat"

{{- $zhwikiVersion := "20220909" }}
[".local/share/fcitx5/pinyin/dictionaries/zhwiki-{{ $zhwikiVersion }}.dict"]
    type = "file"
    url = "https://download.fastgit.org/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-{{ $zhwikiVersion }}.dict"

{{-   $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}

["{{ $fontDir }}/Sarasa Mono SC Nerd Regular.ttf"]
    type = "file"
    url = "https://raw.fastgit.org/laishulu/Sarasa-Mono-SC-Nerd/master/sarasa-mono-sc-nerd-regular.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Sarasa Mono SC Nerd Bold.ttf"]
    type = "file"
    url = "https://raw.fastgit.org/laishulu/Sarasa-Mono-SC-Nerd/master/sarasa-mono-sc-nerd-bold.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Sarasa Mono SC Nerd Italic.ttf"]
    type = "file"
    url = "https://raw.fastgit.org/laishulu/Sarasa-Mono-SC-Nerd/master/sarasa-mono-sc-nerd-italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/Sarasa Mono SC Nerd Bold Italic.ttf"]
    type = "file"
    url = "https://raw.fastgit.org/laishulu/Sarasa-Mono-SC-Nerd/master/sarasa-mono-sc-nerd-bolditalic.ttf"
    refreshPeriod = "168h"
{{- end }}
